name: Format Python Code

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-v1
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Create and activate virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip

    - name: Install YAPF
      run: |
        source .venv/bin/activate
        pip install yapf

    - name: Format Python files
      run: |
        source .venv/bin/activate
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        yapf --style .style.yapf --in-place --recursive .
        git add *.py
        git diff --quiet && git diff --staged --quiet || (git commit -m "style: format Python files with YAPF" && git push) 